spring:

  application:
    name: Data Returns Data Migration

  main:
    web-application-type: NONE

  master-data:
    datasource:
       url: jdbc:postgresql://localhost:5432/dr_md_api
       username: data_returns_owner
       password: data_returns_owner
       driverClassName: org.postgresql.Driver

  submissions:
    datasource:
       url: jdbc:postgresql://localhost:5432/dr_pi_api
       username: data_returns_owner
       password: data_returns_owner
       driverClassName: org.postgresql.Driver

  pidec:
    datasource:
       url: jdbc:postgresql://poimaster.cqcu8oshua9i.eu-west-1.rds.amazonaws.com:5432/pidec?currentSchema=pidec
       username: poimaster
       password: poimaster
       driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: default
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
